apiVersion: apps/v1
kind: Deployment
metadata:
  name: attacker
  namespace: untrusted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attacker
  template:
    metadata:
      labels:
        app: attacker
        security.ybor.ai/access: denied
    spec:
      serviceAccountName: attacker
      containers:
        - name: attacker
          image: curlimages/curl:8.7.1
          imagePullPolicy: IfNotPresent
          command: ["sleep", "3600"]
