apiVersion: apps/v1
kind: Deployment
metadata:
  name: trusted-client
  namespace: trusted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trusted-client
  template:
    metadata:
      labels:
        app: trusted-client
        security.ybor.ai/access: approved
    spec:
      serviceAccountName: trusted-client
      containers:
        - name: trusted-client
          image: trusted-client:demo
          imagePullPolicy: IfNotPresent
